export const INGREDIENT_DETAILS_OPEN = 'INGREDIENT_DETAILS_OPEN'
export const INGREDIENT_DETAILS_CLOSE = 'INGREDIENT_DETAILS_CLOSE'
export const ORDER_DETAILS_OPEN = 'ORDER_DETAILS_OPEN'
export const ORDER_DETAILS_CLOSE = 'ORDER_DETAILS_CLOSE'
